#!/bin/sh

rm $HOME/.config/nvim/init.vim

curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p $HOME/.config/nvim

ln -s $PWD/config/init.vim $HOME/.config/nvim/init.vim

nvim +PlugInstall +q +q

echo "DONE NEOVIM"

