#!/bin/sh

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p $HOME/.config/nvim

cp config/init.vim $HOME/.config/nvim/init.vim

nvim +PlugInstall +q +q

echo "DONE NEOVIM"

