#!/bin/sh

if [[ -z "$XDG_CONFIG_HOME" ]]; then
	CONFIG_PATH="$HOME/.config/nvim"
else
	CONFIG_PATH="$XDG_CONFIG_HOME/nvim"
fi

rm -f $CONFIG_PATH/init.vim
rm -f $CONFIG_PATH/UltiSnips

curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p $CONFIG_PATH

ln -s $PWD/config/init.vim $CONFIG_PATH/init.vim
ln -s $PWD/config/UltiSnips $CONFIG_PATH/UltiSnips
ln -s $PWD/config/lua $CONFIG_PATH/lua

nvim +PlugInstall +qa

echo "dotfiles -- neovim -- installed"

exit 0

